### ISSUE TITLE
overloading private methods

### ISSUE THREAD

**Issue by Wouter1** [coady/multimethod#124]
**Describe the bug**
If the method being overloaded (with @multimethod) is a private method, calling the method seems to fail

**To Reproduce**

```
$ pip list
Package       Version
------------- -------
multimethod   1.10   
pip           20.0.2 
pkg-resources 0.0.0  
setuptools    44.0.0 

```

Now in python commandline do
```
from __future__ import annotations
from multimethod import multimethod
from typing import TypeVar, Type, Optional

class A:
 @multimethod
 def __f(self, x:Optional[int])->int:
  return 1
 @multimethod
 def __f(self, x:int, y:int)->int:
  return 2
 def test(self):
   return self.__f(1)
```

Now call ```A().test()```

**Expected behavior**
prints ```1```

**Actual behavior**
```
>>> A().test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 9, in test
  File "/home/wouter/venv/lib/python3.8/site-packages/multimethod/__init__.py", line 326, in __call__
    func = self[tuple(func(arg) for func, arg in zip(self.type_checkers, args))]
  File "/home/wouter/venv/lib/python3.8/site-packages/multimethod/__init__.py", line 320, in __missing__
    raise DispatchError(msg, types, keys)
multimethod.DispatchError: ('__f: 0 methods found', (<class '__main__.A'>, <class 'int'>), [])
```

My first guess is that the method resolver does not realize that __f results in a mangled name.

**Comment by coady** [comment]
> My first guess is that the method resolver does not realize that __f results in a mangled name.

Yes, the `register` method can be used explicitly instead of the "magic" namespace lookup.
```python
class A:
 @multimethod
 def __f(self, x:Optional[int])->int:
  return 1
 @__f.register
 def _(self, x:int, y:int)->int:
  return 2
```

**Comment by Wouter1** [comment]
@coady thanks for the quick response and confirmation of the issue.
Also thanks for the workaround.

However I believe this case should be handled automatically.
