### ISSUE TITLE
No longer possible to have a chain of overloads without a non-overloaded function as last

### ISSUE THREAD

**Issue by KantiCodes** [coady/multimethod#127]
# Spec:
- python 3.10
- multimethod 2.0rc1

```python
from multimethod import DispatchError, overload

class B:
    @overload
    def f(self, x:str) -> tuple[int]:
        raise ValueError("x must be an int or float")
    
    @overload
    def f(self, x:int|float) -> int:
        return int(x)

b = B()
b.f("str")
>>>
Traceback (most recent call last):
  File "/home/bartek/projects/US/StrategyWorkers/azure-batch-strategy-handler/zzztest.py", line 16, in <module>
    b.f("str")
  File "/usr/lib/python3.10/typing.py", line 2011, in _overload_dummy
    raise NotImplementedError(
NotImplementedError: You should not call an overloaded function. A series of @overload-decorated functions outside a stub module should always be followed by an implementation that is not @overload-ed.
```

**Comment by coady** [comment]
v2.0 removes `overload`. The example is importing `typing.overload`, just passed-through.

Maybe the package should not reference `overload` in its namespace, to force an `ImportError`.

**Comment by coady** [comment]
`multimethod` still works the same.
```python
from multimethod import multimethod

class B:
    @multimethod
    def f(self, x:str) -> tuple[int]:
        raise ValueError("x must be an int or float")
    
    @multimethod
    def f(self, x:int|float) -> int:
        return int(x)
```

**Comment by coady** [comment]
[v2.0rc2](https://github.com/coady/multimethod/releases/tag/v2.0rc2) prevents importing `overload`.
